
ALL:  util unix qlib2 lib330
	@echo Successfully built libsrc

util:: FRC
	(cd util; make -f makefile.ux)

unix:: FRC
	(cd unix; make -f makefile.ux)

qlib2:: FRC
	(cd qlib2; make)

lib330:: FRC
	(cd lib330; make)

clean: FRC
	(cd ../../lib; echo Cleaning in:; pwd; \
	rm -f *.o *.obj  *% *~);
	(cd util; make -f makefile.ux clean)
	(cd unix; make -f makefile.ux clean)
	(cd qlib2; make clean)
 
FRC: 
	

