
#
#                    Nmake File For ringVtanks - Windows NT version
#
NODEBUG=1

!include <ntwin32.mak>

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib


all:
   emake $B\ringvtanks.exe

$B\ringvtanks.exe: ringvtanks.obj
   $(link) $(conlflags) $(ldebug) $(conlibsmt) ringvtanks.obj $L\ws_clientII.obj \
    $L\chron3.obj $L\kom.obj $L\logit.obj $L\socket_ew.obj $L\time_ew.obj \
    $L\getutil.obj $L\transport.obj $L\swap.obj $L\socket_ew_common.obj \
    $L\sleep_ew.obj $L\threads_ew.obj -out:$B\ringvtanks.exe

.c.obj:
   $(cc) $(GLOBALFLAGS)  /nologo $(cflags) $(cdebug) $(cvarsmt) $(tflags) $<


# Clean-up directives
clean:
	del a.out core *.o *.obj *% *~

clean_bin:
	del $B\ringvtanks*
