# Sample makefile for nrts_tap based client

CC     = cc 
INCDIR = idatap-1.2.3/include
LIBDIR = idatap-1.2.3/lib/solaris.5.7.sun4
OPTMIZ = -O 
INCS   = -I$(INCDIR)
#CFLAGS = $(OPTMIZ) $(INCS) -L$(LIBDIR) -D$(OSNAME) -D$(OSTYPE) -DDEBUG_PRINT
CFLAGS = $(OPTMIZ) $(INCS) -L$(LIBDIR)
SOCKLIBS = -lsocket -lnsl
#IDALIBS = -lcssio -lida -lida10  -lisp -lmtio -lmio -lnrts -loldmtio -lparo -lrdio -lsacio -lsclk -lseed -lttyio -lutil -lxfer -lutil -lida10 -lida
IDALIBS =  $(LIBDIR)/libxfer.a $(LIBDIR)/libcssio.a $(LIBDIR)/libida10.a $(LIBDIR)/libida.a $(LIBDIR)/libisp.a $(LIBDIR)/libmtio.a $(LIBDIR)/libmio.a $(LIBDIR)/libnrts.a $(LIBDIR)/libparo.a $(LIBDIR)/librdio.a $(LIBDIR)/libsacio.a $(LIBDIR)/libsclk.a $(LIBDIR)/libseed.a $(LIBDIR)/libttyio.a $(LIBDIR)/libutil.a 

BINARIES = vdl.o vdltrg.o vdlput.o vdlqsub.o ifft512.o ifft1024.o ifft256.o \
	fftlib.o cmprs.o vdlfilt.o filt5.o filtheli.o filt2.o filt10.o datetime.o\
	vdltcp_nopass.o vdlidatap.o 
	
include SCRIPTS/makefile.modules

#*
#*   VDLIDATAP
#*
vdlidatap: $(BINARIES)
	
	$(CC) $(CFLAGS)  $(BINARIES) -o vdlidatap -lm  $(IDALIBS) $(SOCKLIBS)
