# Sample makefile for nrts_tap based client

CC     = gcc 
BIN    = vdlorb
INCDIR = /opt/antelope/4.1/include
INCDIR2 =  ../STEIM123
BINDIR = ../bin/$(PLATFORM)
LIBDIR = ../vdl
OPTMIZ = -O
INCS   = -I$(INCDIR) -I$(INCDIR2)
OSNAME = SOLARIS
OSNAME2 = SOLARIS2
cflags = $(OPTMIZ) $(INCS) -L$(dLIBDIR) -D$(OSNAME) -D$(OSNAME2) -DDEBUG_PRINT  -ansi
#cflags = $(OPTMIZ) $(INCS) -L$(LIBDIR) -D$(OSNAME) -D$(OSNAME2) -ansi
ldlibs = -lpkt -lorb $(TRLIBS) $(SVR4LIBS)


OBJS = vdl.o vdltrg.o vdlput.o vdlqsub.o ifft512.o ifft1024.o ifft256.o \
	fftlib.o cmprs.o vdlfilt.o filt5.o filtheli.o filt2.o filt10.o datetime.o\
	feedme_orb.o feedme_test_null.o vdltcp_nopass.o vdlmath.o

include $(ANTELOPEMAKE).gcc
include SCRIPTS/makefile.modules

#*
#*	VDL From an ORBSERVER
#*
$(BIN) : $(OBJS) 
	$(CC) $(CFLAGS) $(OBJS) -o vdlorb $(LDFLAGS) $(LDLIBS) 
