#
#                     Make file for makehbfile
#                         Unix Version
#
CFLAGS = -g -D__unix

O = makehbfile.o config.o chdir_sol.o mkdir_sol.o rename_sol.o

all: makehbfile

makehbfile: $O
	cc -o makehbfile $O -lm  -lc

clean:
	/bin/rm -f makehbfile *.o

clean_bin:
	/bin/rm -f makehbfile
