drop Sequence CubeVersionSeq;
drop TABLE CubeVersionNumber;
drop Sequence AuditCustomDeliverySeq;
drop TABLE AuditCustomDelivery;
drop Sequence AuditQddsDeliverySeq;
drop TABLE AuditQddsDelivery;
drop Sequence AuditPhoneDeliverySeq;
drop TABLE AuditPhoneDelivery;
drop Sequence AuditPagerDeliverySeq;
drop TABLE AuditPagerDelivery;
drop Sequence AuditEmailDeliverySeq;
drop TABLE AuditEmailDelivery;
drop Sequence AlarmsAuditSeq;
drop TABLE AlarmsAudit;
drop VIEW RuleDeliveryRecipient;
drop Sequence AlarmsRuleSeq;
drop TABLE AlarmsRule;
drop Sequence AlarmsFormatSeq;
drop TABLE AlarmsFormat;
drop Sequence CustomDeliverySeq;
drop TABLE CustomDelivery;
drop Sequence QddsDeliverySeq;
drop TABLE QddsDelivery;
drop Sequence PhoneDeliverySeq;
drop TABLE PhoneDelivery;
drop Sequence PagerDeliverySeq;
drop TABLE PagerDelivery;
drop Sequence EmailDeliverySeq;
drop TABLE EmailDelivery;
drop Sequence AlarmsCritSeq;
drop TABLE CriteriaProgram;
drop Sequence RecipientDeliverySeq ;
drop TABLE RecipientDelivery ;
drop Sequence AlarmsRecipientSeq;
drop TABLE AlarmsRecipient;

