#
#    $Id: makefile.ux,v 1.1 2005/07/26 20:18:53 friberg Exp $
#
#    Revision history:
#     $Log: makefile.ux,v $
#     Revision 1.1  2005/07/26 20:18:53  friberg
#     added in UNIX make
#

LIBS = -lpthread
CFLAGS = ${GLOBALFLAGS}
B = $(EW_HOME)/$(EW_VERSION)/bin
L = $(EW_HOME)/$(EW_VERSION)/lib


file2ring: file2ring.o $L/getutil.o $L/transport.o $L/sleep_ew.o
	cc -o $B/file2ring file2ring.o $L/getutil.o $L/transport.o \
	$L/sleep_ew.o $L/kom.o $(LIBS)


lint:
	lint file2ring.c $(GLOBALFLAGS)

# Clean-up rules
clean:
	rm -f a.out core *.o *.obj *% *~

clean_bin:
	rm -f $B/file2ring*
