#! /bin/csh

# C-shell script to re-make all parts of the 
# Eartworm version of RCV

unalias cd
unalias rm

echo --------------------------------------------
echo "Making STEIM123"
pwd
cd ${EW_HOME}/${EW_VERSION}/src/data_exchange/rcv/STEIM123
rm *.o
make -f makefile steim123
cd ..

echo --------------------------------------------
echo "Making rcv & station"
cp makefile.sol.sunrcv sunrcv/makefile.sol
cd sunrcv
mv makefile makefile.ketchum
rm *.o
make -f makefile.sol
cd ..

echo "Finished making rcv."
