# $Id: Makefile.linux,v 1.1 2006/11/16 23:25:16 ilya Exp $
########################################################################
# Linux definitions
# COMMENTS: $(UTILDIR)/timeutil.c removed from the timeutil.o target line
#           Switching to gcc
#           Removing +w, which warns about all questionable constructs in aCC.  
#           Putting -DLINUX flag as a default
CC	= gcc
INCL	= ../include
CFLAGS	= -I$(INCL)  -DLINUX 
RANLIB = ranlib 
########################################################################

########################################################################
# Solaris 2 definitions
#
#$CC	= cc
#INCL	= ../include
#CFLAGS	= -I$(INCL) +w -DSOLARIS2 -g
#LDLIBS	= -lposix4 -lnsl -lsocket
#RANLIB	= /bin/true

########################################################################
# SunOS definitions
#
#CC	= acc
#INCL	= ../include
#CFLAGS	= -I$(INCL)
#LDLIBS	=
#RANLIB	= ranlib

########################################################################

LIB	= libutil.a

OBJECTS = service.o cfgutil.o stuff.o seedutil.o timeutil.o # mmutil.o 


.PRECIOUS:	$(LIB)

ALL =		$(LIB)

all:		$(ALL)

$(LIB):		$(LIB)($(OBJECTS))
		$(RANLIB) $@

timeutil.o:	$(INCL)/dpstruc.h $(INCL)/quanstrc.h $(INCL)/service.h \
		$(INCL)/stuff.h 
		$(CC) -c $(CFLAGS) timeutil.c

seedutil.o:	$(INCL)/dpstruc.h $(INCL)/quanstrc.h $(INCL)/service.h \
		$(INCL)/seedstrc.h $(INCL)/stuff.h seedutil.c
		$(CC) -c $(CFLAGS) seedutil.c

mmutil.o:	$(INCL)/dpstruc.h $(INCL)/quanstrc.h $(INCL)/service.h \
		$(INCL)/stuff.h mmutil.c
		$(CC) -c $(CFLAGS) mmutil.c

service.o:	$(INCL)/dpstruc.h $(INCL)/service.h $(INCL)/stuff.h \
		service.c
		$(CC) -c $(CFLAGS) service.c

cfgutil.o:	$(INCL)/dpstruc.h cfgutil.c $(INCL)/stuff.h
		$(CC) -c $(CFLAGS) cfgutil.c

stuff.o:	$(INCL)/dpstruc.h stuff.c
		$(CC) -c $(CFLAGS) stuff.c

clean:
		-rm *.o $(LIB)

veryclean:	clean
		-rm *.o *~ *% $(LIB)

install:
