#                    Nmake File For import_ida - Windows NT version

NODEBUG=1

!include <ntwin32.mak>

APP = import_ida
O = main.obj client.obj forward.obj hbeat.obj init.obj params.obj \
#    pinno.obj \ #   Pin # functionality removed 2005/04/20
    reformat.obj signals.obj

B = $(EW_HOME)\$(EW_VERSION)\bin
L = $(EW_HOME)\$(EW_VERSION)\lib


$B\$(APP).exe: $O
   $(link) $(conlflags) $(ldebug) $(conlibsmt) $O $L\threads_ew.obj \
    $L\getutil.obj $L\kom.obj $L\logit_mt.obj \
    $L\transport.obj $L\sleep_ew.obj \
    $L\time_ew.obj $L\sema_ew.obj ..\idatap\idatap.lib -out:$B\$(APP).exe

.c.obj:
   $(cc) $(GLOBALFLAGS)  /nologo /I..\idatap\include $(cflags) $(cdebug) $(cvarsmt) $(tflags) -D_NTSDK $<


# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~

clean_bin:
	-del $B\import_ida*
